#3.1 About a Python:
#Python Version Check

In [1]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


#3.2 Data Types in Python.

In [2]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)
# Trying to modify the tuple (will raise an error)
# my_tuple.append(4) # Uncommenting this line will raise an AttributeError

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [3]:
#my_tuple.append(4)

#3.2.1 Some Common Data Types in Python:

Numeric:

In [4]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


#Sequence:

Data Types - Sequence - String

In [5]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


Data Types - Sequence - List

In [6]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

Data Types - Sequence - Tuple

In [7]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


In [8]:
#colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

('red', 'green', 'yellow', 'blue')

#Mapping:

Data Types - Sequence - Dict

In [9]:
person = {'name':'John','age':30,'city':'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


#Set:

Data Types - Set

In [10]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


#Boolean:

Data Types - Boolean

In [11]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


#Special:

Data Types - Boolean

In [12]:
result = None

#3.3 Logical Statements and Loops.

Python code can be decomposed into packages, modules, statements, and expressions, as follows:
1. Expressions create and process objects:
• Expressions are part of statements that return a value, such as variables, operators, or function
calls.
2. Statements contain expressions:

• Statements are sections of code that perform an action. The main groups of Python state-
ments are: assignment statements, print statements, conditional statements (if, break, con-
tinue, try), and looping statements (for, while).

3. Module Contain statements:
• Modules are Python files that contain Python statements, and are also called scripts.
4. Packages are composed of modules:
• Packages are Python programs that collect related modules together within a single directory
hierarchy.

#3.4 Logical Statements:

Logical statements are used to perform conditional operations. The primary logical statements in Python
are:
• if: Executes a block of code if the condition is true.
if condition:
# Code to execute if condition is true

• elif: Short for ”else if,” allows for multiple conditions to be checked sequentially.
if condition1:
# Code for condition1
elif condition2:
# Code for condition2

• else: Executes a block of code if none of the preceding conditions are true.
if condition:
# Code if condition is true
else:
# Code if condition is false

Sample Code - if-else statement

In [13]:
num = 10
if num > 0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Non-positive")

Positive


Comparison operators: Used to compare values.

– ==: Equal to

– !=: Not equal to

– <: Less than

– >: Greater than

– <=: Less than or equal to

– >=: Greater than or equal to

Sample Code - Comparision Operator

In [14]:
x = 5
y = 10
if x > 0 and y < 20:
  print("Both conditions are true")
if x > 0 or y > 20:
  print("At least one condition is true")
if not x == 0:
  print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


Logical operators: Used to combine multiple conditions.

– and: True if both conditions are true.

– or: True if at least one condition is true.

– not: Inverts the truth value of the condition.

In [15]:
# Define two boolean variables
a = True
b = False
# Using the ’and’ operator
if a and b:
  print("Both a and b are True")
else:
  print("Either a or b is False") # This will be printed
# Using the ’or’ operator
if a or b:
  print("At least one of a or b is True") # This will be printed
else:
  print("Both a and b are False")
# Using the ’not’ operator
if not a:
  print("a is False") # This will not be printed
else:
  print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


#3.4.1 Loops:

Sample Code - Various Loops

In [16]:
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
  print(fruit)
# While loop:
count = 0
while count < 5:
  print("Count is:", count)
  count += 1
# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
  print(fruit)
  if fruit == "apple":
    break
# Continiue
print("loop 2")
for fruit in fruits:
  if fruit == "apple":
    continue
  else:
    print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


#3.5 Functions.

Functions are fundamental building blocks in Python, similar to mathematical functions that define
relationships between inputs and outputs. In mathematics, a function such as

z = f(x, y)

maps inputs x and y to an output z.
However, functions in programming languages are more generalized and versatile; they can process
various data types and perform a wide range of operations on inputs beyond simple mathematical
relationships.
A function in programming is a self-contained block of code that encapsulates a specific task or a set
of related tasks. It defines how inputs relate to outputs through the operations performed within the
function. When a function is called, input arguments are provided, the program executes the defined
code, and then returns the function’s output. This structure enables functions to manage complex
processes in a structured and reusable way. Most programming languages offer support for pre-built
and user-defined functions to promote following:
1. Code Abstraction and Re-usability: A key principles in software development. Rather than
repeating the same code across multiple locations in an application, we can define a single function
that performs the desired task and call it wherever needed. This approach not only reduces
redundancy but also simplifies maintenance; if a change is required, we modify it in one place—the
function itself—rather than updating every instance where the code appears.
2. Code Modularity: By breaking down complex processes into smaller, self-contained functions
that focus on specific tasks, we create modular code that is both organized and easier to understand.
This modular structure enhances readability and maintainability, making it simpler to update or
expand the program without disrupting its overall structure.

#3.6 Anatomy of a Function:

Here’s a brief overview of the main components of a function:
• Function Name: This is the identifier by which the function is called. It should be descriptive,
conveying the function’s purpose or the task it performs. In Python, function names typically
follow snake case formatting (e.g., calculate_area).


• Input Parameters: These are variables listed within the parentheses after the function name in
the definition. Parameters allow functions to accept inputs, which are used within the function’s
body to perform calculations or operations. Parameters make functions more flexible and reusable,
as they allow you to pass different values each time you call the function.

• Docstring: A docstring is an optional, multi-line comment placed just after the function defini-
tion. It provides documentation on the function’s purpose, parameters, and output, helping others

understand what the function does. In Python, a docstring is written within triple quotes (”””
”””) and can be accessed using the help() function.
• Return Output: The return statement specifies the output of the function, allowing it to send
back a result to the part of the program where it was called. This enables further processing or
storage of the function’s output. If no return statement is specified, the function will return
None by default.

In [17]:
def add_binary(a, b):
    """
    Returns the sum of two decimal numbers in binary digits.
    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer
    Returns:
    binary_sum (str): Binary string of the sum of a and b
    """
    binary_sum = bin(a+b)[2:]
    return binary_sum

Example on Built - in - Function

In [18]:
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class ’int’>
total = sum([1, 2, 3]) # Output: 6

Hello, World!


#3.6.2 Built - in - Methods:

#3.6.3 User - Defined - Function:

Example of well-structured user-defined function

In [41]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.
    This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
    Fahrenheit to Celsius)
    and then asks for the temperature value. It calculates and returns the converted temperature.
    Returns:
    float: The converted temperature value.
    """
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")
    if choice == "1":
      # Celsius to Fahrenheit conversion
      celsius = float(input("Enter temperature in Celsius: "))
      fahrenheit = (celsius * 9/5) + 32
      print(f"{celsius}C is equal to {fahrenheit}F")
      return fahrenheit
    elif choice == "2":
      # Fahrenheit to Celsius conversion
      fahrenheit = float(input("Enter temperature in Fahrenheit: "))
      celsius = (fahrenheit - 32) * 5/9
      print(f"{fahrenheit}F is equal to {celsius}C")
      return celsius
    else:
      print("Invalid choice. Please enter 1 or 2.")
      return None
# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 2
Enter temperature in Fahrenheit: 39.5
39.5F is equal to 4.166666666666667C


4.166666666666667

#4 TO - DO - Task

4.1 Exercise on Functions:

Task - 1:

In [42]:
#Unit Conversion Program
def convert_units(conversion_type, value):
    if conversion_type == 1:
        return value * 3.28084
    elif conversion_type == 2:
        return value / 3.28084
    elif conversion_type == 3:
        return value * 2.20462
    elif conversion_type == 4:
        return value / 2.20462
    elif conversion_type == 5:
        return value * 0.264172
    elif conversion_type == 6:
        return value / 0.264172

print("1: meters->feet  \n2: feet->meters")
print("3: kg->lbs      \n4: lbs->kg")
print("5: liters->gallons \n6: gallons->liters")

try:
    c = int(input("Enter conversion type: "))
    v = float(input("Enter value: "))
    print("Converted:", convert_units(c,v))
except:
    print("Invalid input")


1: meters->feet  
2: feet->meters
3: kg->lbs      
4: lbs->kg
5: liters->gallons 
6: gallons->liters
Enter conversion type: 3
Enter value: 2.2
Converted: 4.850164


Task - 2:

In [43]:
# Sum, Average, Max, Min from user list
def find_sum(nums):
    return sum(nums)

def find_avg(nums):
    return sum(nums)/len(nums)

def find_max(nums):
    return max(nums)

def find_min(nums):
    return min(nums)

try:
    numbers=input("Enter numbers separated by space: ")
    nums=[float(x) for x in numbers.split()]
    print("Sum:",find_sum(nums))
    print("Average:",find_avg(nums))
    print("Max:",find_max(nums))
    print("Min:",find_min(nums))
except:
    print("Invalid input")


Enter numbers separated by space: 10 28 32
Sum: 70.0
Average: 23.333333333333332
Max: 32.0
Min: 10.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:

In [22]:
#Extract every other element
lst=[1,2,3,4,5,6]
print(lst[::2])

[1, 3, 5]


2.

In [23]:
# Sublist
lst=[1,2,3,4,5,6]
print(lst[2:5])

[3, 4, 5]


3.

In [24]:
#Reverse list
lst=[1,2,3,4,5]
print(lst[::-1])

[5, 4, 3, 2, 1]


4.

In [25]:
#Remove first and last
lst=[1,2,3,4,5]
print(lst[1:-1])

[2, 3, 4]


5.

In [26]:
# First N elements
lst=[1,2,3,4,5]
print(lst[:3])

[1, 2, 3]


6.

In [27]:
#Last N elements
lst=[1,2,3,4,5]
print(lst[-2:])

[4, 5]


7.

In [28]:
# Reverse skipping
lst=[1,2,3,4,5,6]
print(lst[-2::-2])

[5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:

In [29]:
# Flatten Nested List
def flatten(lst):
    r=[]
    for i in lst:
        if isinstance(i,list):
            r+=flatten(i)
        else:
            r.append(i)
    return r

print(flatten([[1,2],[3,4],[5]]))


[1, 2, 3, 4, 5]


2.

In [30]:
# Access nested element
lst=[[1,2,3],[4,5,6],[7,8,9]]
print(lst[1][2])

6


3.

In [31]:
#Sum nested list
def sum_nested(lst):
    s=0
    for i in lst:
        if isinstance(i,list):
            s+=sum_nested(i)
        else:
            s+=i
    return s

print(sum_nested([[1,2],[3,[4,5]],6]))

21


4.

In [32]:
#Remove element
def remove_element(lst,val):
    r=[]
    for i in lst:
        if isinstance(i,list):
            r.append(remove_element(i,val))
        elif i!=val:
            r.append(i)
    return r

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


5.

In [33]:
# Max in nested list
def find_max(lst):
    m=float('-inf')
    for i in lst:
        if isinstance(i,list):
            m=max(m,find_max(i))
        else:
            m=max(m,i)
    return m

print(find_max([[1,2],[3,[4,5]],6]))

6


6.

In [34]:
# Count occurrences
def count_occ(lst,val):
    c=0
    for i in lst:
        if isinstance(i,list):
            c+=count_occ(i,val)
        elif i==val:
            c+=1
    return c

print(count_occ([[1,2],[2,3],[2,4]],2))

3


7.

In [35]:
# Deep flatten
def deep_flatten(lst):
    r=[]
    for i in lst:
        if isinstance(i,list):
            r+=deep_flatten(i)
        else:
            r.append(i)
    return r

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8.

In [36]:
#Average nested list
def flatten(lst):
    r=[]
    for i in lst:
        if isinstance(i,list):
            r+=flatten(i)
        else:
            r.append(i)
    return r

f=flatten([[1,2],[3,4],[5,6]])
print(sum(f)/len(f))

3.5


#10 To - Do - NumPy

10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [37]:
import numpy as np

# 1. Initialize an empty array with size 2x2
arr1 = np.empty((2,2))
print("1. Empty array (2x2):\n", arr1)

# 2. Initialize an all one array with size 4x2
arr2 = np.ones((4,2))
print("\n2. Ones array (4x2):\n", arr2)

# 3. Array filled with a specific value
arr3 = np.full((3,3), 7)
print("\n3. Array filled with value 7:\n", arr3)

# 4. Zeros array with same shape and type as arr2
arr4 = np.zeros_like(arr2)
print("\n4. Zeros like arr2:\n", arr4)

# 5. Ones array with same shape and type as arr4
arr5 = np.ones_like(arr4)
print("\n5. Ones like arr4:\n", arr5)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\n6. List converted to numpy array:\n", arr6)

1. Empty array (2x2):
 [[4.06935756e-315 0.00000000e+000]
 [6.63272224e-310 1.92218462e+227]]

2. Ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like arr2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

5. Ones like arr4:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

6. List converted to numpy array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [38]:
# 1. Array with values from 10 to 49
arr1 = np.arange(10,50)
print("1. Values from 10 to 49:\n", arr1)

# 2. Create 3x3 matrix with values 0 to 8
arr2 = np.arange(9).reshape(3,3)
print("\n2. 3x3 matrix from 0 to 8:\n", arr2)

# 3. Create 3x3 identity matrix
arr3 = np.eye(3)
print("\n3. Identity matrix:\n", arr3)

# 4. Random array of size 30 and find mean
arr4 = np.random.random(30)
print("\n4. Random array:\n", arr4)
print("Mean:", arr4.mean())

# 5. 10x10 random array with min and max
arr5 = np.random.random((10,10))
print("\n5. Random 10x10 array:\n", arr5)
print("Minimum:", arr5.min())
print("Maximum:", arr5.max())

1. Values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array:
 [0.67921432 0.20440356 0.95823623 0.52743827 0.07784028 0.81048618
 0.19351935 0.45454158 0.22103025 0.52647455 0.55806758 0.0482887
 0.3626838  0.12588536 0.01482529 0.66939926 0.09270317 0.19220741
 0.28743331 0.14918182 0.94992443 0.60510832 0.84592605 0.67319794
 0.03061984 0.52380921 0.618863   0.18020695 0.2890154  0.75944828]
Mean: 0.420999323179473

5. Random 10x10 array:
 [[0.70745872 0.27538891 0.07318437 0.50224319 0.8856716  0.77402927
  0.40136649 0.28257438 0.25220052 0.29234076]
 [0.10028891 0.57205375 0.27691922 0.57994205 0.25781736 0.49864065
  0.24107253 0.89449972 0.88936216 0.01573726]
 [0.12142509 0.12320321 0.46746292 0.83082101 0.26778335 0.461668
  0.76657311 0.12533047 0.22442109 0

In [39]:
# 6. Zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6. Zero array with 5th element replaced:\n", arr6)

# 7. Reverse an array
arr7 = np.array([1,2,0,0,4,0])
print("\n7. Reversed array:\n", arr7[::-1])

# 8. 2D array with 1 on border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
print("\n8. Border array:\n", arr8)

# 9. 8x8 checkerboard pattern
arr9 = np.zeros((8,8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9. Checkerboard pattern:\n", arr9)


6. Zero array with 5th element replaced:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
 [0 4 0 0 2 1]

8. Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

In [40]:
#Array operations
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print(x-y)
print(x*3)
print(x**2)
print(np.dot(v, w))
print(np.dot(x, v))
print(np.dot(x, y))
print(np.concatenate((x, y), axis=0))

vw_column = np.column_stack((v, w))
print(vw_column)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


Problem - 4: Matrix Operations:

In [44]:
#Matrix operations
A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

In [45]:
#Prove A * A^-1 = I

A_inv = np.linalg.inv(A)

print("\nInverse of A:")
print(A_inv)

identity_check = np.dot(A, A_inv)

print("\nA * A^-1 :")
print(identity_check)


Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1 :
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [46]:
#Prove AB ≠ BA


AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nA * B =")
print(AB)

print("\nB * A =")
print(BA)

print("\nAre AB and BA equal?")
print(np.array_equal(AB, BA))


A * B =
[[23 13]
 [51 29]]

B * A =
[[36 44]
 [13 16]]

Are AB and BA equal?
False


In [47]:
#Prove (AB)^T = B^T A^T


AB_T = (AB).T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T =")
print(AB_T)

print("\nB^T * A^T =")
print(BT_AT)

print("\nAre they equal?")
print(np.array_equal(AB_T, BT_AT))


(AB)^T =
[[23 51]
 [13 29]]

B^T * A^T =
[[23 51]
 [13 29]]

Are they equal?
True


In [48]:
# Solve Linear Equations using Matrix Method
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([[-1],
                 [-3],
                 [9]])

print("\nCoefficient Matrix A:")
print(A_eq)

print("\nConstant Matrix B:")
print(B_eq)


Coefficient Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant Matrix B:
[[-1]
 [-3]
 [ 9]]


In [49]:
# Solve using Inverse Method
A_eq_inv = np.linalg.inv(A_eq)

X = np.dot(A_eq_inv, B_eq)

print("\nSolution using Inverse Method (X = A^-1 B):")
print("x =", X[0][0])
print("y =", X[1][0])
print("z =", X[2][0])


Solution using Inverse Method (X = A^-1 B):
x = 2.0
y = 1.0
z = -2.0


In [50]:
# Solve directly using np.linalg.inv()
X2 = np.linalg.inv(A_eq).dot(B_eq)

print("\nSolution using np.linalg.inv function:")
print("x =", X2[0][0])
print("y =", X2[1][0])
print("z =", X2[2][0])


Solution using np.linalg.inv function:
x = 2.0
y = 1.0
z = -2.0


10.2 Experiment: How Fast is Numpy?

In [51]:
#NumPy vs Python speed
import time

size=1000000
a=list(range(size))
b=list(range(size))

start=time.time()
c=[a[i]+b[i] for i in range(size)]
print("Python time:",time.time()-start)

x=np.arange(size)
y=np.arange(size)

start=time.time()
z=x+y
print("NumPy time:",time.time()-start)

Python time: 0.10988163948059082
NumPy time: 0.004642486572265625
